[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"


[project]
dynamic = ["version"]
name = "ggpeps"  
description = "A Python package to work with Gauged Gaussian Projected Entangled Pair States (GGPEPS)"
readme = "README.md"
requires-python = ">=3.9"

#license = {file = "LICENSE.txt"}

keywords = ["physics", "quantum physics", "simulation", "tensor networks"]

authors = [
  {name = "Patrick Emonts", email = "emonts@lorentz.leidenuniv.nl" },
  {name = "Ariel Kelman", email = "ariel.kelman@mail.huji.ac.il" }
]

maintainers = [
  {name = "Patrick Emonts", email = "emonts@lorentz.leidenuniv.nl" },
  {name = "Ariel Kelman", email = "ariel.kelman@mail.huji.ac.il" }
]

classifiers = [
  "Development Status :: 3 - Alpha",

  "Intended Audience :: Physics",
  "Topic :: Simulation",

  # Pick your license as you wish
  #TODO: Fix this
  "License :: OSI Approved :: MIT License",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
  "numpy",
  "scipy",
  "pandas",
  "tqdm",
  "numba",
  "matplotlib",
  "sympy",
  "pfapack",
  "jax",
  "jaxlib",
  "ray",
  # py-pfaffian is not available on PyPI, so we get it from GitHub:
  "py-pfaffian @ git+https://github.com/Nuclear-Physics-with-Machine-Learning/PyPfaffian.git@main"
]

[project.optional-dependencies]
dev = ["check-manifest", "seaborn", "black"]
test = ["coverage", "nox"]

[tool.setuptools_scm]
version_file = "src/ggpeps/_version.py"

[tool.black]
line-length = 119

[[tool.mypy.overrides]]
# mark packages which do not have typing data, 
# see: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
module = ["numba.*", "pfapack.*", "py_pfaffian.*", "sympy.*"]
ignore_missing_imports = true

#[project.urls]
#"Homepage" = ""
#"Bug Reports" = ""
#"Source" = ""

# If there are data files included in your packages that need to be
# installed, specify them here.
# package-data = {"ggpeps" = ["misc/*.dat"]}
