#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./tjob.out.%j
#SBATCH -e ./tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J 4x4sf_g_1.7_el_0.8500_mag_0.2941_int_1.0_mass_0.0
# Queue (Partition):
#SBATCH -A alex-account
#SBATCH --partition=alexq
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
# Number of cpus
#SBATCH --cpus-per-task=4
#SBATCH -c 4
#SBATCH --mem-per-cpu=6GB
#
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ariel.kelman@mail.huji.ac.il
#
# Wall clock limit:
#SBATCH --time=0

#Load some modules
module purge
source ~/.pyenv/gaussianenv/bin/activate

PROJECTS=/usr/people/snirgaz/arielkelman/projects/gaussian-peps

# Run the program: 
srun python $PROJECTS/manager.py min-mc 4 --fermions --ncopy 2 --nlayer 2 --params paramvec.npy --warmup_steps 50000 --meas_steps 120000 --update_size 8 --nrunner 4 --g 1.7 --int 1.0 --mass 0.0

if [ -d /tmp/ray ]
then
	rm -rf /tmp/ray
fi

