#!/bin/bash -l

# Standard output and error:
#SBATCH -o ./tjob.out.%j
#SBATCH -e ./tjob.err.%j

# Initial working directory:
#SBATCH -D ./

# Job Name:
#SBATCH -J L4_g_1.1_el_0.5500_mag_0.4545_int_1.0_mass_1.0

# Queue (Partition):
#SBATCH -A all-account
#SBATCH --partition=allq,infiniq

# Number of nodes and MPI tasks per node:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1

# Number of cpus
#SBATCH --cpus-per-task=4
#SBATCH -c 4
#SBATCH --mem-per-cpu=2GB

#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ariel.kelman@mail.huji.ac.il
#
# Wall clock limit:
#SBATCH --time=7-00:00:00

#Load some modules
module purge
source ~/.pyenv/ggpeps/bin/activate

PROJECTS=/usr/people/snirgaz/arielkelman/projects/gaussian-peps

# Run the program: 
srun python $PROJECTS/manager.py min-mc 4 --fermions --ncopy 2 --num_pg_layer 1 --num_fermionic_layer 1 --params paramvec.npy --nrunner 4 --warmup_steps 40000 --meas_steps 120000 --update_size 8 --ignore_cache_eval --g 1.1 --int 1.0 --mass 1.0

if [ -d /tmp/ray ]
then
	rm -rf /tmp/ray
fi

