#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pandas as pd
import sys,os

def main(args):
    fnamevec = args.fnames
    # Check whether the outputfile exists already
    if os.path.exists(args.outfile):
        print("Outputfile exists already. Aborting here.", file = sys.stderr)
        sys.exit(1)

    dfvec = []
    for fname in fnamevec:
        if os.path.isfile(fname):
            df_tmp = pd.read_pickle(fname)
            dfvec.append(df_tmp)
        else:
            print(f"No such file {fname}. Skipping.")
    
    df = pd.concat(dfvec)
    df.to_pickle(args.outfile)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("fnames", nargs="+", help="Filenames to be merged")
    parser.add_argument("--outfile", default = "merge.pkl", help="Output filename")
    args = parser.parse_args()

    main(args)