#!/bin/bash
set -eu
for fname in $@
do
  subs1=${fname##paramvec_}
  subs2=${subs1/_extracted_paramvec} 
  foldername=${subs2%%.npy}
  if [ ! -d $foldername ]
  then
    mkdir $foldername
  fi
  mv "$fname" "$foldername/paramvec.npy"
done

