#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from ggpeps import utils

def main():
    for fname in args.fname:
        utils.extract_params_from_results_file(fname)
        

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("fname", nargs="+", type=str, help="input filename")
    args = parser.parse_args()

    main()