#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import numpy as np


def main(fnames):
    for fname in fnames:
        if os.path.isfile(fname):
            data = np.genfromtxt(fname, delimiter="\n")
            basename = os.path.basename(fname)
            name, ext = os.path.splitext(basename)
            name_out = name + ".npy"
            np.save(name_out, data)
        else:
            print(f"File '{fname}' not found. Skipping.")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument("fnames", nargs="+", type=str, help="txt files")
    args = parser.parse_args()
    main(args.fnames)
